### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by usama7628674** [DarkSecDevelopers/LitePhish#1]
@graysuit

**Comment by graysuit** [comment]
@usama7628674 welcome
Happy to see you since long time. Its lite version of [grayfish](https://github.com/graysuit/grayfish).

**Comment by graysuit** [comment]
sorry I clicked close accidently

**Comment by graysuit** [comment]
Now you can test, its launched.

**Comment by sTiKyt** [comment]
You answered question, closing here.
