### ISSUE TITLE
[REQUEST] Method to send credientials via Webhook Discord and Telegram AP

### ISSUE THREAD

**Issue by coolerspeex** [DarkSecDevelopers/LitePhish#13]
**Credientials send to Discord webhook and Telegram API**
It will be a better thing and better then the email sending.

**Comment by graysuit** [comment]
hmmmm, nice idea !
I wanna finish it soon.
Thanks.

**Comment by graysuit** [comment]
@coolerspeex 
Please check now.
You need to change values according to situation.
- for discord: just uncomment lines and replace webhook link with yours
- for telegram: just uncomment lines and replace token and chat_id with yours

https://github.com/DarkSecDevelopers/LitePhish/blob/main/sender/config.php
