### ISSUE TITLE
I cant see the templates !

### ISSUE THREAD

**Issue by elixirop** [DarkSecDevelopers/LitePhish#14]
![Screenshot from 2021-03-23 15-34-04](https://user-images.githubusercontent.com/68217482/112228063-e3c85880-8bed-11eb-9210-0054b6cd1495.png)

I have issue trying in local host with Ubuntu , could you help me to fix that please !

**Comment by graysuit** [comment]
@elixirop That;s not bug.
You need to run both:
- apache (html,css,js)
- mysql (php,sql)

so here mysql is not running. So that's why you are seeing raw php code instead of running that php code.

**Comment by elixirop** [comment]
Actually  I run both and the same :  Any ideas?
![Screenshot from 2021-03-24 15-07-10](https://user-images.githubusercontent.com/68217482/112389937-c01b1600-8cb2-11eb-90a8-486de6a1cfec.png)

**Comment by elixirop** [comment]
I already fix it, thanks !

**Comment by graysuit** [comment]
@elixirop 
Show the fix, 
so that future users may take help as well.
