### ISSUE TITLE
Add Pubg phishing page

### ISSUE THREAD

**Issue by swagkarna** [DarkSecDevelopers/LitePhish#16]

**Comment by prateek-chaubey** [comment]
@swagkarna Yes , it needs to be added

**Comment by graysuit** [comment]
Sure,
It will be added soon.

**Comment by graysuit** [comment]
@swagkarna 
Prateek has added pubg fake UC generator phishing page.
https://github.com/DarkSecDevelopers/LitePhish#hall-of-fame
